// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkkkzluhsoxvqbkzhfkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBra2t6bHVoc294dnFia3poZmt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTk5NzQsImV4cCI6MjA1ODg5NTk3NH0.Dv6BGAfE60agwdMnkBUx6zhj9YgPM4dYERVfyxc1fuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);