
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgjgrdicuveemtriproj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnamdyZGljdXZlZW10cmlwcm9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NTc4NTQsImV4cCI6MjA2MzAzMzg1NH0.SVegj54ZSas15kWcsHNPzrLM4ixAK-t6T2NxWFKRA_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
